'use strict';
Object.assign(paths,{flame:'M12 3c2 4 6 6 6 11a6 6 0 0 1-12 0c0-3 1-5 3-7v5c3-2 4-5 3-9Z',snow:'M12 2v20M3.3 7l17.4 10M3.3 17 20.7 7M9 4l3 3 3-3M9 20l3-3 3 3M3 10l4-1-1-4M21 14l-4 1 1 4M6 19l1-4-4-1M18 5l-1 4 4 1',wallet:'M3 6h17v15H3z M3 6V3h14v3M15 12h5v5h-5z',clipboard:'M8 4H4v17h16V4h-4M8 2h8v5H8z M8 12h8m-8 4h5'});
function effectiveLead(l){return {...l,status:stage(l)}}
function priorityFor(l){return WorkflowCore.priority(effectiveLead(l),task(l.id),local.priorities?.[l.id])}
inFilter=function(l,f=statusFilter){return WorkflowCore.filter(effectiveLead(l),f,task(l.id),local.priorities?.[l.id])};
function dueLead(l){return !WorkflowCore.terminal(stage(l))&&WorkflowCore.due(task(l.id))}
function temperatureHTML(l,button=false){const p=priorityFor(l);if(!p)return '';return `<${button?'button':'span'} class="temperature ${p.value}" ${button?'data-priority-menu':''} title="${esc(p.reason)}${p.manual?' · Manual':' · Automatic'}" ${button?'aria-label="Change lead priority"':''}>${icon(p.value==='hot'?'flame':'snow')}<span>${p.value.toUpperCase()}</span>${button?icon('chevron'):''}</${button?'button':'span'}>`}
const experienceCard=card;card=function(l){let html=experienceCard(l);html=html.replace('class="lead-card ',`class="lead-card ${dueLead(l)?'follow-due ':''}`);if(!selectMode)html=html.replace(badge(stage(l)),`<div class="card-state">${temperatureHTML(l)}${badge(stage(l))}</div>`);if(dueLead(l))html=html.replace('class="card-reminder"','class="card-reminder due-reminder"');return html};
function leadGroup(l){return dueLead(l)?'due':({'New / Transferred':'new',Opened:'opened',Called:'called'})[stage(l)]||'rest'}
filtered=function(){const rank={due:0,new:1,opened:2,called:3,rest:4};return ALL.filter(l=>inFilter(l)&&matches(l)).sort((a,b)=>{if(!query){const d=rank[leadGroup(a)]-rank[leadGroup(b)];if(d)return d;if(dueLead(a)&&dueLead(b))return task(a.id).at-task(b.id).at}return sort==='name'?String(a.name).localeCompare(String(b.name)):sort==='oldest'?(a.sent_ts||0)-(b.sent_ts||0):sort==='status'?statuses.indexOf(stage(a))-statuses.indexOf(stage(b)):lastActivity(b)-lastActivity(a)})};
boardResults=function(){const all=filtered(),shown=all.slice(0,limit),grouped=!query&&!['sold','closed'].includes(statusFilter);const groups=[['due','Follow-ups due','Ready to call','calendar'],['new','New opportunities','Unopened','bolt'],['opened','Opened','Needs action','file'],['called','Called','Status pending','phone'],['rest','Everything else','','grid']];const content=all.length?(grouped?groups.map(([key,title,sub,symbol])=>{const a=shown.filter(l=>leadGroup(l)===key);return a.length?`<section class="lead-group ${key==='due'?'due-group':''}"><h2 class="lead-group-title">${icon(symbol)}${title}<span>${sub?'— '+sub:''}</span><b>${all.filter(l=>leadGroup(l)===key).length}</b></h2><div class="cards">${a.map(card).join('')}</div></section>`:''}).join(''):shown.map(card).join('')):'<div class="empty"><h2>No matching leads</h2><p>Try another name, business or filter.</p><button class="btn" data-action="reset-filters">Clear search & filters</button></div>';$('#lead-results').innerHTML=`${selectMode?`<div class="select-line"><label><input type="checkbox" class="selection-check" id="select-all" ${all.length&&all.every(l=>selection.has(l.id))?'checked':''}>Select all ${all.length} results</label><span>${selection.size} selected</span></div>`:''}<div class="cards ${grouped?'grouped-cards':''}">${content}</div><div class="list-bottom"><span>${all.length?`1–${Math.min(limit,all.length)} of ${all.length}`:'0 leads'}</span>${all.length>limit?'<button class="btn" data-action="more">Show 36 more</button>':''}</div><div id="bulk-area">${bulkHTML()}</div>`;if($('#select-all'))$('#select-all').onchange=e=>{all.forEach(l=>e.target.checked?selection.add(l.id):selection.delete(l.id));boardResults()};wireSelection();arrangeBulk($('#lead-results'));updateArrivalCue()};
function updateArrivalCue(){const all=$('[data-filter="all"]'),n=unreadLeads().length;if(all){all.classList.toggle('arrival-cue',statusFilter!=='all'&&n>0);if(n&&statusFilter!=='all')all.title=n+' unopened leads · View All'} }
function priorityMenu(){const l=byId[selected],p=priorityFor(l);if(!p)return;modal('Lead priority',l.name,`<p class="helper">${esc(p.reason)} · ${p.manual?'Manual':'Automatic'}</p><div class="priority-options">${[['hot','flame','HOT','Actively work this opportunity'],['cold','snow','COLD','Lower urgency; keep scheduled reminders'],['auto','refresh','Automatic','Use the last update and the 7-day window']].map(([value,symbol,title,sub])=>`<button data-priority-choice="${value}" ${isReadOnly()?'disabled':''}>${icon(symbol)}<span><strong>${title}</strong><small>${sub}</small></span>${icon((p.manual?p.value:'auto')===value?'checkcircle':'chevron')}</button>`).join('')}</div><p class="error" id="form-error" role="alert"></p>`,'<button class="btn" data-action="close">Close</button>')}
function redesignLeadHeader(l){
 const header=$('.detail-head'),line=$('.detail-head .identity-line');
 if(!header||!line)return;
 header.classList.add('lead-header-v2');
 const body=$('.detail-body');if(body){body.tabIndex=0;body.setAttribute('role','region');body.setAttribute('aria-label',detailTab==='info'?'Lead information':'Lead activity');}
 const receipt=`<div class="lead-receipt"><strong>${esc(l.id)}</strong>${l.sent_ts?`<span class="context-dot">·</span><time>${esc(exactDate(l.sent_ts))}</time>`:''}</div>`;
 const status=badge(stage(l)).replace('</span>',`${icon('chevron')}</span>`);
 line.className='lead-hero';
 const statusButton=`<button class="pipeline-control" data-action="status" aria-label="Update status: ${esc(label(stage(l)))}" ${isReadOnly()?'disabled':''}>${status}</button>`;
 line.innerHTML=`<div class="lead-identity">${receipt}<h1>${esc(l.name||'Unnamed contact')}</h1><div class="lead-business">${businessIcon(l)}<div class="lead-business-copy">${l.business?`<p class="business">${esc(l.business)}</p>`:''}<p class="business-location"><span>${esc(l.type||'Business')}</span>${l.state?`<span class="business-state">${esc(l.state)}</span>`:''}</p></div></div><div class="lead-workflow-controls">${statusButton}<div class="desktop-priority">${temperatureHTML(l,true)}</div></div></div><div class="lead-controls">${clockHTML(l)}<div class="mobile-priority">${temperatureHTML(l,true)}</div></div>`;
 header.querySelector('.right-actions')?.remove();
 $('.mobile-detail-actions')?.remove();
 const tabs=$('.detail-tabs'),contacts=header.querySelector('.contact-actions');
 if(tabs){const bar=document.createElement('div');bar.className='lead-header-bar';bar.append(tabs);if(contacts){contacts.querySelector('.phone-label')?.remove();bar.append(contacts)}header.append(bar)}
 document.querySelectorAll('.contact-actions [data-native-contact],.contact-actions [data-contact],#dock [data-native-contact],#dock [data-contact]').forEach(button=>{const channel=button.dataset.nativeContact||button.dataset.contact,labels={call:'CALL',text:'TEXT',whatsapp:'WPP'};if(labels[channel])button.innerHTML=icon(channel==='call'?'phone':channel==='text'?'message':'whatsapp')+labels[channel]});

}
const experienceDetail=renderDetail;renderDetail=function(){experienceDetail();const l=byId[selected];redesignLeadHeader(l);const names={'Contact':'users','Business profile':'briefcase','Financials':'wallet','Coverage answers':'shield','Must know':'flag','Follow-up':'calendar','Requested coverage':'shield','Business research':'search','Add a note':'edit','Policy':'clipboard','Quote':'clipboard','Quote & policy':'clipboard','Policy & appointments':'clipboard','Appointments':'calendar','Life insurance':'shield','Investment':'wallet','Annuity':'wallet','Closure':'flag','Notes':'edit','Policy details':'clipboard'};document.querySelectorAll('.section-label').forEach(h=>{const title=h.textContent.trim();h.innerHTML=icon(names[title]||'file')+esc(title)});const grid=$('.info-grid');if(grid){const finance=$('[data-info-group="Financials"]'),coverage=$('[data-info-group="Coverage answers"]');if(finance||coverage){const compact=document.createElement('div');compact.className='facts-pair';if(finance)compact.append(finance);if(coverage)compact.append(coverage);$('.info-column')?.append(compact)}document.querySelectorAll('.facts-pair dt').forEach(dt=>{const old=dt.textContent;dt.textContent=({'Currently insured':'Insured?','Quoted elsewhere':'Other quotes?','Annual policy':'Annual policy?','FT employees':'Full-time staff'})[old]||old;dt.title=old})}normalizeDetailCards(l);if(dueLead(l))$('.lead-header-bar').insertAdjacentHTML('beforebegin',`<div class="due-detail">${icon('calendar')}<span>Follow-up due · ${esc(fullDate(task(l.id).at))}. Call to mark it attended.</span></div>`);applySessionUI()};
const experiencePolicy=policyHTML;policyHTML=function(l){
  if(l.hector)return hectorPolicyCards(l);
  const e=events().find(e=>e.leadId===l.id&&e.kind==='status'&&(e.status==='Quoted'||/^Quoted\b/.test(e.text))),j=l.jenny||{},quoted=stage(l)==='Quoted'||!!e;
  if(!quoted)return commercialPolicyCard(l);
  const sold=stage(l)==='Bound / Sold',premium=e?.quotedPremium??(stage(l)==='Quoted'?j.premium:null),hasPremium=premium!==null&&premium!==undefined&&premium!=='',amount=hasPremium?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(String(premium).replace(/[$,]/g,''))):'Not recorded',at=e?.at||(stage(l)==='Quoted'?l.updated_ts:0),date=at?exactDate(at):'Date unavailable';
  return `<section class="side-section quote-section"><div class="quote-heading"><h2 class="section-label">${sold?'Quote & policy':'Quote'}</h2>${badge(sold?'Bound / Sold':'Quoted')}</div><div class="quote-stat"><span>Quoted premium</span><button class="quote-amount" ${hasPremium?`data-copy="${esc(amount)}" title="Copy quoted premium"`:''}>${esc(amount)}</button></div><p class="quote-date">${icon('clock')}<span>${e?.at?'Quoted':at?'Status updated':'Quote date'} · <time ${at?`datetime="${new Date(at).toISOString()}"`:''}>${esc(date)}</time></span></p>${sold?`<dl class="policy-facts">${row('Policy premium',j.premium)}${row('Term (months)',j.term)}${row('Commission (%)',j.agent_comm)}${row('Extra fee',j.fee)}</dl>`:''}${j.loss_reason?`<dl>${row('Loss reason',j.loss_reason)}</dl>`:''}</section>`;
};
const experienceTimeline=timeline;timeline=function(a,within=false){return experienceTimeline(a.map(e=>{let text=e.text||'';if(e.kind==='followup'&&e.dueAt)text=(e.done?'Follow-up completed':'Follow-up scheduled · '+fullDate(e.dueAt)+' '+localTZLabel)+(e.note?' · '+e.note:'');else text=text.replace(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z/g,v=>fullDate(Date.parse(v))+' '+localTZLabel);const value=e.value||(/priority:\s*(hot|cold|auto)\b/i.exec(text)||[])[1]?.toLowerCase();const iconKey=['priority','priority_auto'].includes(e.kind)?value==='cold'?'snow':value==='hot'?'flame':'refresh':undefined;return {...e,text,iconKey}}),within)};
eventLabels.priority='Priority changed';eventIcons.priority='flame';eventLabels.priority_auto='Automatic priority changed';eventIcons.priority_auto='refresh';
// Notifications remain actionable until the due task is attended, never cleared by opening.
dueNotices=function(){return ALL.filter(dueLead).sort((a,b)=>task(a.id).at-task(b.id).at)};
noticeModal=function(){const due=dueNotices(),fresh=unreadLeads(),a=noticeTab==='leads'?fresh:due;modal('Notifications',`${due.length+fresh.length} need attention`, `<div class="notification-tabs"><button data-notice-tab="leads" class="${noticeTab==='leads'?'active':''}">New leads <b>${fresh.length}</b></button><button data-notice-tab="follow" class="${noticeTab==='follow'?'active':''}">Due now <b>${due.length}</b></button></div><div class="notice-list">${a.length?a.map(l=>`<button class="notice-row ${noticeTab==='follow'?'due-notice':''}" data-notice-open="${esc(l.id)}">${noticeTab==='follow'?icon('calendar'):businessIcon(l)}<span><strong>${esc(l.name)}</strong><small>${esc(l.id)} · ${esc(l.business)}</small><em>${noticeTab==='follow'?'Due · '+esc(fullDate(task(l.id).at)):'Received · '+esc(exactDate(l.sent_ts))}</em></span>${icon('chevron')}</button>`).join(''):`<div class="notice-empty">${icon('checkcircle')}<h3>${noticeTab==='follow'?'No follow-ups due':'No unopened leads'}</h3><p>${noticeTab==='follow'?'Reminders appear at the scheduled time and stay until you call or complete them.':'New leads appear here until opened.'}</p></div>`}</div>`,'<button class="btn" data-action="close">Close</button>');$('#modal').classList.add('notifications-modal')};
// A coherent agenda with separate pending and completed states, sharing exact-time rules.
followLeads=function(){return ALL.filter(l=>!WorkflowCore.terminal(stage(l))&&!local.tasks[l.id]?.done&&(task(l.id)||stage(l)==='Follow-Up'))};
followFiltered=function(){const completed=followFilter==='completed',a=completed?completedFollowLeads():followLeads();return a.filter(l=>{const t=l._completedTask||local.tasks[l.id],at=completed?t?.completedAt:t?.at,key=at?dateKey(new Date(at)):'';if(!matches(l))return false;if(followFilter==='today'&&key!==today())return false;if(followFilter==='past'&&!dueLead(l))return false;if(followFilter==='upcoming'&&(!t||t.at<=Date.now()))return false;if(followFilter==='undated'&&t?.at)return false;if(dateFrom&&(!key||key<dateFrom))return false;if(dateTo&&(!key||key>dateTo))return false;return true}).sort((a,b)=>completed?((b._completedTask||local.tasks[b.id]).completedAt||0)-((a._completedTask||local.tasks[a.id]).completedAt||0):(task(a.id)?.at||Infinity)-(task(b.id)?.at||Infinity))};
renderFollowups=function(){const pending=followLeads(),due=pending.filter(dueLead).length,todayCount=pending.filter(l=>task(l.id)&&dateKey(new Date(task(l.id).at))===today()).length,completed=completedFollowLeads().length;$('#main').innerHTML=`<div class="page agenda-page"><div class="page-title"><div class="title-line"><h1>Follow-ups</h1><span class="total">${pending.length}</span></div>${noticeButton()}<button class="btn" data-action="add-follow">${icon('plus')}Schedule</button></div><div class="agenda-overview"><div><span>Today</span><strong>${todayCount}</strong></div><div class="overdue-stat"><span>Due now</span><strong>${due}</strong></div><div><span>Upcoming</span><strong>${pending.filter(l=>task(l.id)?.at>Date.now()).length}</strong></div><div><span>Completed</span><strong>${completed}</strong></div></div><div class="agenda-layout"><aside class="agenda-sidebar"><div class="agenda-caption">Your calendar<span>Select a day to see its follow-ups</span></div>${calendarHTML(calMonth,'agenda')}</aside><section class="agenda-list">${searchTools()}<div class="filters">${[['today','Today'],['past','Due now'],['upcoming','Upcoming'],['all','All pending'],['completed','Completed'],['undated','No date']].map(([f,title])=>`<button class="filter ${followFilter===f?'active':''}" data-follow-filter="${f}" aria-pressed="${followFilter===f}">${title}</button>`).join('')}</div><div class="follow-tools"><button class="btn agenda-dates" data-agenda-range>${icon('calendar')}${dateFrom?esc(dateFrom===dateTo?dateFrom:dateFrom+' — '+dateTo):'Date range'}</button>${dateFrom?'<button class="btn ghost" data-agenda-reset>Clear dates</button>':''}</div><div id="follow-results"></div></section></div></div>`;followResults();wireSearch(followResults);finishChrome();};
followResults=function(){const a=followFiltered(),completed=followFilter==='completed';$('#follow-results').innerHTML=`${a.length&&!completed?`<div class="select-line"><label><input class="selection-check" id="select-follow-all" type="checkbox" ${a.every(l=>selection.has(l.id))?'checked':''}>Select all ${a.length}</label><span>${selection.size} selected</span></div>`:''}<div class="follow-list">${a.map(l=>{const t=l._completedTask||local.tasks[l.id],done=!!t?.done;return `<article class="agenda-item ${done?'completed':dueLead(l)?'due':''}">${!completed?`<input class="selection-check" type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.name)}" ${selection.has(l.id)?'checked':''}>`:icon('checkcircle')}<div class="agenda-time"><strong>${t?.at?esc(timeLabel(t.at)):'No time'}</strong><span>${t?.at?esc(dateLabel(t.at)):'No date'}</span></div><div class="agenda-person"><button class="follow-client" data-open="${esc(l.id)}">${esc(l.name)}</button><p>${esc(l.business)} · ${esc(l.id)}</p>${t?.note?`<p class="agenda-note">${icon('edit')}${esc(t.note)}</p>`:''}<small class="agenda-state">${done?`${t.completionMethod==='closed'?'Closed with lead':t.completionMethod==='call'?'Attended · Call requested':'Completed'}${isReadOnly()?' by '+esc(t.completedBy||'Agent'):''} · ${t.completedAt?esc(exactDate(t.completedAt)):'Date unavailable'}`:dueLead(l)?'Due now · Call to attend':'Scheduled'}</small></div>${!done?`<button class="btn" data-schedule-id="${esc(l.id)}">${t?'Edit':'Set date'}</button>`:''}</article>`}).join('')||`<div class="empty"><h2>${completed?'No completed follow-ups':'No follow-ups in this view'}</h2><p>${followFilter==='today'?'Nothing scheduled today. Upcoming includes later today and future dates.':'Choose another view or schedule a follow-up from a lead.'}</p></div>`}</div><div id="bulk-area">${completed?'':bulkHTML()}</div>`;wireSelection();if($('#select-follow-all'))$('#select-follow-all').onchange=e=>{a.forEach(l=>e.target.checked?selection.add(l.id):selection.delete(l.id));followResults()};arrangeBulk($('#follow-results'))};
const experienceStatusFields=statusFields;statusFields=function(){experienceStatusFields();if($('#status-value')?.value==='Declined')$('#status-fields').innerHTML=''};
let declineDraft={note:'',reason:''};
function declineModal(){
  const l=byId[selected];if(!l)return;
  const note=$('#status-note')?.value;declineDraft={note:note===undefined?declineDraft.note:note,reason:$('#reason')?.value||declineDraft.reason};
  modal('Decline lead',`${l.name} · ${l.id}`,`<input type="hidden" id="status-value" value="Declined"><div class="decline-intro">${icon('flag')}<p>Choose the main reason this opportunity is closing.</p></div><input type="hidden" id="reason" value="${esc(declineDraft.reason)}"><p class="reason-label" id="decline-reason-label">Decline reason</p><div class="decline-reasons" role="radiogroup" aria-labelledby="decline-reason-label" aria-describedby="form-error">${WorkflowCore.reasons.map((r,i)=>`<button type="button" role="radio" aria-checked="${r===declineDraft.reason}" tabindex="${r===declineDraft.reason||(!declineDraft.reason&&i===0)?0:-1}" class="reason-option ${r===declineDraft.reason?'chosen':''}" data-decline-reason="${esc(r)}"><span class="reason-icon">${icon(['briefcase','wallet','users','shield','pin','calendar','close','phone','copy','more'][i])}</span><span>${esc(r)}</span><span class="reason-check">${icon('check')}</span></button>`).join('')}</div><label class="form-field">Note <span class="optional">· optional</span><textarea id="status-note" placeholder="Add details for your records">${esc(declineDraft.note)}</textarea></label><p class="error" id="form-error" role="alert"></p>`,`<button class="btn" data-decline-back>Back</button><button class="btn primary" data-action="save-status">Save declined</button>`);
}

function setLoading(active,message='Loading…'){let el=$('#workspace-loading');if(!el){el=document.createElement('div');el.id='workspace-loading';el.setAttribute('role','status');el.setAttribute('aria-live','polite');document.body.append(el)}el.hidden=!active;el.innerHTML=active?`<div class="loading-card"><span class="loading-ring"></span><strong>${esc(message)}</strong><div class="loading-track"><span></span></div></div>`:'';$('#main')?.setAttribute('aria-busy',String(active))}
// Handle extra choices before legacy event handlers; all writes keep server role checks.
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.view==='followups'){followFilter='today';dateFrom='';dateTo='';selection.clear()}
if(b.dataset.declineReason){e.preventDefault();e.stopImmediatePropagation();chooseDeclineReason(b);return}
if(b.dataset.statusChoice==='Declined'){e.preventDefault();e.stopImmediatePropagation();declineDraft={note:$('#status-note')?.value||'',reason:''};declineModal();return}
if(b.hasAttribute('data-decline-back')){e.preventDefault();e.stopImmediatePropagation();declineDraft={note:$('#status-note')?.value||'',reason:$('#reason')?.value||''};statusModal();if($('#status-note'))$('#status-note').value=declineDraft.note;return}
if(b.dataset.noticeOpen){e.preventDefault();e.stopImmediatePropagation();close();openLead(b.dataset.noticeOpen);return}
if(b.hasAttribute('data-priority-menu')){priorityMenu();return}if(b.dataset.priorityChoice){e.preventDefault();e.stopImmediatePropagation();if(isReadOnly())return;const id=selected;b.disabled=true;try{if(IS_LOCAL_PREVIEW){local.priorities||={};local.priorities[id]={value:b.dataset.priorityChoice==='auto'?null:b.dataset.priorityChoice};persist()}else{const r=await connectedWrite('priority',{id,value:b.dataset.priorityChoice,version:local.priorities?.[id]?.version||0});local.priorities=r.priorities}close();render();refreshConnectedHistory().catch(()=>{})}catch(err){$('#form-error').textContent=err.message}finally{b.disabled=false}return}
if(b.dataset.action==='save-status'&&$('#status-value')?.value==='Declined'&&!$('#reason')?.value){e.preventDefault();e.stopImmediatePropagation();$('#form-error').textContent='Choose a decline reason before saving.';$('#reason')?.focus()}
},true);
let attentionKey='',lastAppBadge=-1;function tickAttention(){if(!currentSession)return;const key=[today(),...dueNotices().map(l=>l.id+':'+task(l.id).version),...unreadLeads().map(l=>l.id)].join('|');if(key!==attentionKey){attentionKey=key;updateBells();updateArrivalCue();if(!selected&&!backgroundViewBusy()){if(view==='leads')passiveRender(renderLeads);if(view==='followups')passiveRender(renderFollowups)}}const count=dueNotices().length+unreadLeads().length;if(count!==lastAppBadge&&navigator.setAppBadge&&document.visibilityState==='visible'){lastAppBadge=count;(count?navigator.setAppBadge(count):navigator.clearAppBadge?.())?.catch(()=>{})}}
setInterval(tickAttention,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tickAttention()});
const experienceLeads=renderLeads;renderLeads=function(){experienceLeads();const total=$('.title-line .total');if(total)total.textContent=ALL.filter(l=>inFilter(l)).length;updateArrivalCue()};

function chooseDeclineReason(button){
  if(!$('#reason'))return;$('#reason').value=button.dataset.declineReason;declineDraft.reason=button.dataset.declineReason;
  document.querySelectorAll('[data-decline-reason]').forEach(b=>{const chosen=b===button;b.classList.toggle('chosen',chosen);b.setAttribute('aria-checked',String(chosen));b.tabIndex=chosen?0:-1});if($('#form-error'))$('#form-error').textContent='';
}
document.addEventListener('keydown',e=>{const b=e.target.closest('[data-decline-reason]');if(!b||!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const a=[...document.querySelectorAll('[data-decline-reason]')],i=a.indexOf(b),n=e.key==='Home'?0:e.key==='End'?a.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+a.length)%a.length;chooseDeclineReason(a[n]);a[n].focus()});

function completedFollowLeads(){return local.completed?local.completed.filter(t=>byId[t.leadId]).map(t=>({...byId[t.leadId],_completedTask:t})):ALL.filter(l=>local.tasks[l.id]?.done)}

// Normalize every information card, including future additional-information sections.
for(const key of ['annual revenue','annual payroll','subcontractor costs','pt employees'])if(!GROUPS[2][1].includes(key))GROUPS[2][1].push(key);
function displayMoney(value){if(value===null||value===undefined||value==='')return '';const n=Number(String(value).replace(/[$,]/g,''));return Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n):String(value)}
function hectorPolicyCards(l){const h=l.hector,appointments=[['First appointment',h.appt1],['Second appointment',h.appt2]].filter(x=>x[1]);const products=[['Life insurance',h.life_prem,'Monthly premium',h.life_sold],['Investment',h.inv_amount,'Amount',h.inv_sold],['Annuity',h.ann_amount,'Amount',h.ann_sold]].filter(x=>x[1]!==null&&x[1]!==undefined&&x[1]!==''||x[3]);return `${appointments.length?`<section class="side-section compact-facts"><h2 class="section-label">Appointments</h2><dl>${appointments.map(x=>row(...x)).join('')}</dl></section>`:''}${products.map(([title,amount,label,date])=>`<section class="side-section product-card"><h2 class="section-label">${esc(title)}</h2>${amount!==null&&amount!==undefined&&amount!==''?`<div class="quote-stat"><span>${esc(label)}</span><span class="quote-amount">${esc(displayMoney(amount))}</span></div>`:''}${date?`<p class="quote-date">${icon('checkcircle')}Sold · ${esc(date)}</p>`:''}</section>`).join('')}${h.loss_reason?`<section class="side-section compact-facts"><h2 class="section-label">Closure</h2><dl>${row('Reason',h.loss_reason)}</dl></section>`:''}`}
function normalizeDetailCards(l){
 document.querySelectorAll('.info-section,.side-section').forEach(section=>{
  const dl=section.querySelector(':scope>dl'),rows=dl?[...dl.querySelectorAll('.field-row')]:[];
  if(dl&&!rows.length&&!section.querySelector('.quote-stat,.quote-date')){section.remove();return}
  if(rows.length){section.classList.add('data-card');rows.forEach(r=>{const label=r.querySelector('dt')?.textContent||'',value=r.querySelector('dd')?.textContent||'';r.classList.toggle('inline-fact',value.length<=34&&!/description|address|email|business name|category|reason/i.test(label));r.classList.toggle('wide-fact',value.length>65||/description|address|email|business name|category|reason/i.test(label));});}
 });
 const research=$('.research-end');if(research&&!research.querySelector('button'))research.remove();
 const note=$('.side-section:has(#note-draft)');if(note){
  const draft=note.querySelector('#note-draft'),footer=note.querySelector('.note-footer'),saved=events().filter(e=>e.leadId===l.id&&e.kind==='note'),h=note.querySelector('h2');h.innerHTML=icon('edit')+'Notes';
  const recent=document.createElement('div');recent.className='recent-note';recent.innerHTML=saved.length?`<p>${esc(saved[0].text)}</p><small>${saved[0].at?esc(exactDate(saved[0].at)):'Date unavailable'}</small><button class="note-history" data-tab="activity">${saved.length>1?'View '+saved.length+' notes':'Read note'} in Activity ${icon('chevron')}</button>`:'<p class="empty-note">No saved notes yet.</p>';h.after(recent);
  if(isReadOnly()){draft.remove();footer?.remove()}else{const compose=document.createElement('details');compose.className='note-compose';compose.open=!!local.drafts[l.id];compose.innerHTML=`<summary>${icon('plus')}Add a note</summary>`;compose.append(draft);if(footer)compose.append(footer);note.append(compose)}
 }
 const follow=$('.side-section:has(.schedule-data)');if(follow){follow.classList.add('follow-card');const data=follow.querySelector('.schedule-data'),p=data.querySelector('p'),t=task(l.id);if(t){p.textContent=t.note||'';if(!t.note)p.remove();const label=document.createElement('small');label.className='schedule-zone';label.textContent=localTZLabel;data.querySelector('strong')?.after(label)}}
 document.querySelectorAll('.section-label').forEach(h=>{if(!h.querySelector('svg'))h.insertAdjacentHTML('afterbegin',icon('file'))});
}

function commercialPolicyCard(l){const j=l.jenny||{},rows=[['Commission (%)',j.agent_comm],['Extra fee',j.fee!==null&&j.fee!==undefined&&j.fee!==''?displayMoney(j.fee):null],['Term (months)',j.term],['Loss reason',j.loss_reason]].filter(x=>x[1]!==null&&x[1]!==undefined&&x[1]!==''),hasPremium=j.premium!==null&&j.premium!==undefined&&j.premium!=='';if(!hasPremium&&!rows.length)return '';return `<section class="side-section compact-facts product-card"><h2 class="section-label">Policy details</h2>${hasPremium?`<div class="quote-stat"><span>Policy premium</span><button class="quote-amount" data-copy="${esc(displayMoney(j.premium))}" title="Copy policy premium">${esc(displayMoney(j.premium))}</button></div>`:''}${rows.length?`<dl>${rows.map(x=>row(...x)).join('')}</dl>`:''}</section>`}

function refreshVisibleNoteSummary(){const el=$('.recent-note');if(!el||!selected)return;const saved=events().filter(e=>e.leadId===selected&&e.kind==='note');el.innerHTML=saved.length?`<p>${esc(saved[0].text)}</p><small>${saved[0].at?esc(exactDate(saved[0].at)):'Date unavailable'}</small><button class="note-history" data-tab="activity">${saved.length>1?'View '+saved.length+' notes':'Read note'} in Activity ${icon('chevron')}</button>`:'<p class="empty-note">No saved notes yet.</p>'}
