'use strict';
// Shared presentation for every account; data and permissions come from the session.
Object.assign(paths,{logout:'M9 5H5v14h4M14 8l4 4-4 4M8 12h10',sort:'M4 6h16M7 12h10M10 18h4',shield:'M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z m-4 9 3 3 5-6'});
card=function(l){const t=task(l.id),ts=lastActivity(l),[,color]=businessStyle(l);return `<article class="lead-card compact-card ${color} ${stage(l)==='New / Transferred'?'new':''} ${selection.has(l.id)?'selected':''} ${arrival===l.id?'fresh-animate':''}" data-card="${esc(l.id)}"><div class="card-topline"><span title="Received ${esc(exactDate(l.sent_ts))}"><b>${esc(l.id)}</b><span aria-hidden="true"> · </span><time>${esc(exactDate(l.sent_ts))}</time></span>${selectMode?`<input class="card-select" type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.name)}" ${selection.has(l.id)?'checked':''}>`:badge(stage(l))}</div><button class="card-body" data-open="${esc(l.id)}">${businessIcon(l)}<span class="card-identity"><span class="card-name">${esc(l.name||'Unnamed contact')}</span>${l.business&&l.business.trim().toLowerCase()!==String(l.name).trim().toLowerCase()?`<span class="card-business">${esc(l.business)}</span>`:''}<span class="card-type">${esc(l.type||'Business')}${l.state?' · '+esc(l.state):''}</span></span></button><div class="card-bottomline"><div class="card-coverages">${(l.coverages||[]).slice(0,2).map(c=>`<span class="cov">${esc(c)}</span>`).join('')}${l.coverages?.length>2?`<span class="cov">+${l.coverages.length-2}</span>`:''}</div><span class="activity-age" title="Since last activity · ${esc(exactDate(ts))}">${icon('clock')}<span data-elapsed="${ts}">${elapsed(ts)}</span></span></div>${t?`<div class="card-reminder">${icon('calendar')} ${esc(fullDate(t.at))}</div>`:''}</article>`};
filtered=function(){const rank=l=>({'New / Transferred':0,Opened:1,Called:2})[stage(l)]??3;return ALL.filter(l=>inFilter(l)&&matches(l)).sort((a,b)=>{if(statusFilter==='all'&&!query){const group=rank(a)-rank(b);if(group)return group}if(arrival===a.id)return -1;if(arrival===b.id)return 1;return sort==='name'?String(a.name).localeCompare(String(b.name)):sort==='oldest'?(a.sent_ts||0)-(b.sent_ts||0):sort==='status'?statuses.indexOf(stage(a))-statuses.indexOf(stage(b)):lastActivity(b)-lastActivity(a)})};
if(!GROUPS[0][1].includes('business name'))GROUPS[0][1].unshift('business name');
const finishInfo=infoGroups;
infoGroups=function(l){const entries=(l.details||[]).filter(x=>!/^business name$|^dot$/i.test(x[0]));entries.unshift(['Business Name',l.business||'Not provided']);const copy={...l,details:entries};let html=finishInfo(copy);const host=document.createElement('div');host.innerHTML=html;const sections=[...host.querySelectorAll('.info-section')];const contact=sections.find(s=>s.querySelector('h2')?.textContent.trim()==='Contact');const businessRow=[...host.querySelectorAll('.field-row')].find(r=>r.querySelector('dt')?.textContent==='Business Name');if(contact&&businessRow)contact.querySelector('dl').prepend(businessRow);let business=sections.find(s=>s.querySelector('h2')?.textContent.trim()==='Business profile');if(l.dot&&!business){business=document.createElement('section');business.className='info-section';business.innerHTML='<h2 class="section-label">Business profile</h2><dl></dl>';host.append(business)}if(l.dot&&business){const r=document.createElement('div');r.className='field-row dot-row';r.innerHTML=`<dt>DOT</dt><dd><button class="dot-link" data-action="insurance" aria-label="Open insurance information for DOT ${esc(l.dot)}">${esc(l.dot)} ${icon('chevron')}</button></dd>`;const category=[...business.querySelectorAll('.field-row')].find(r=>/^category$/i.test(r.querySelector('dt')?.textContent));category?category.after(r):business.querySelector('dl').append(r)}sections.forEach(s=>{if(!s.querySelector('.field-row'))s.remove()});return host.innerHTML};
const finishDetail=renderDetail;
renderDetail=function(){finishDetail();const l=byId[selected],identity=$('.identity');identity.innerHTML=`${businessIcon(l)}<div class="identity-copy"><div class="id-status"><span>${esc(l.id)}</span>${badge(stage(l))}<time title="Received">${esc(exactDate(l.sent_ts))}</time></div><h1>${esc(l.name||'Unnamed contact')}</h1><p class="business">${esc(l.business||'')}</p><p class="detail-business-type">${esc(l.type||'Business')}${l.state?' · '+esc(l.state):''}</p></div>`;const paper=$('.info-paper');if(paper){const sections=[...paper.children],a=document.createElement('div'),b=document.createElement('div');a.className=b.className='info-column';sections.forEach(section=>{const title=section.querySelector('h2')?.textContent||'';section.dataset.infoGroup=title.trim();(/Contact|Financials/.test(title)?a:b).append(section)});paper.append(a,b);const coverage=document.querySelector(".detail-side .side-section:has(.coverage-pills)");if(coverage){coverage.dataset.infoGroup="Requested coverage";a.append(coverage)}}finishChrome();};
const watchedFilters=new Set(),filterResize=new ResizeObserver(entries=>entries.forEach(({target})=>target._updateFade?.()));
function fadeFilters(){watchedFilters.forEach(el=>{if(!el.isConnected){filterResize.unobserve(el);watchedFilters.delete(el)}});document.querySelectorAll('.filters').forEach(el=>{if(el.parentElement.classList.contains('filter-scroll'))return;const wrap=document.createElement('div');wrap.className='filter-scroll';el.before(wrap);wrap.append(el);el.setAttribute('aria-label','Filter results; swipe horizontally for more');const update=()=>{wrap.classList.toggle('more-left',el.scrollLeft>2);wrap.classList.toggle('more-right',el.scrollWidth-el.clientWidth-el.scrollLeft>2)};el.addEventListener('scroll',update,{passive:true});el._updateFade=update;filterResize.observe(el);watchedFilters.add(el);requestAnimationFrame(()=>{el.querySelector('.active')?.scrollIntoView({block:'nearest',inline:'nearest'});update()})})}
function finishChrome(){fadeFilters();document.querySelectorAll('.page-title,.head-nav').forEach(head=>{if(head.querySelector('[data-signout]'))return;head.insertAdjacentHTML('beforeend',`<button class="notification-bell signout-button" data-signout aria-label="Sign out" title="Sign out">${icon('logout')}</button>`)});const dropdown=$('#sort');if(dropdown){const b=document.createElement('button');b.className='btn sort-button';b.dataset.sortMenu='';b.setAttribute('aria-label','Sort leads: '+dropdown.selectedOptions[0].textContent);b.innerHTML=icon('sort')+`<span>${sortLabels[sort]||dropdown.selectedOptions[0].textContent}</span>`;dropdown.replaceWith(b)}if(typeof applySessionUI==='function')applySessionUI()}
for(const name of ['renderLeads','renderFollowups','renderActivity']){const original=window[name];window[name]=function(){original();finishChrome()}}
const sortLabels={newest:'Recent activity',oldest:'Oldest received',name:'Name A–Z',status:'By status'};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.hasAttribute('data-sort-menu'))modal('Sort leads','Choose how to order your leads',`<div class="sort-options">${Object.entries(sortLabels).map(([v,t])=>`<button data-sort-choice="${v}" aria-pressed="${v===sort}">${icon(v===sort?'checkcircle':'sort')}<span>${t}</span></button>`).join('')}</div>`,'<button class="btn" data-action="close">Cancel</button>');if(b?.dataset.sortChoice){sort=b.dataset.sortChoice;close();renderLeads()}},true);
// Keep list filters mutually understandable: Upcoming starts tomorrow; Today includes today's overdue items.
const followFilterOriginal=followFiltered;followFiltered=function(){let a=followFilterOriginal();if(dateFrom&&dateTo&&dateFrom>dateTo)return [];return a};
let filterObserver=new MutationObserver(()=>{if(!$('#main .filters:not(.filter-scroll .filters)'))return;fadeFilters()});filterObserver.observe($('#main'),{childList:true,subtree:true});
window.addEventListener('online',()=>toast('Connection restored'));
window.addEventListener('offline',()=>toast('You’re offline. Reconnect before saving changes.'));
// Visual viewport is reduced by Safari's keyboard; never leave the contact dock over a form.
function keyboardLayout(){document.body.classList.toggle('keyboard-open',!!window.visualViewport&&innerHeight-visualViewport.height>140)}
visualViewport?.addEventListener('resize',keyboardLayout);

const finalFollowResults=followResults;followResults=function(){finalFollowResults();const summary=$('.follow-summary');if(summary){const invalid=dateFrom&&dateTo&&dateFrom>dateTo;summary.textContent=invalid?'End date must be on or after start date.':`Times shown in ${localTZLabel}. Leads without a saved date appear under “No date”.`;summary.classList.toggle('error',!!invalid)}};
// Build the grouped board once: previous iterations rendered every card twice.
boardResults=function(){const all=filtered(),shown=all.slice(0,limit),groups=[['new','New','Opportunity','bolt'],['opened','Opened','Needs action','file'],['called','Called','Status pending','phone'],['rest','Everything else','','grid']];const groupKey=l=>({'New / Transferred':'new',Opened:'opened',Called:'called'})[stage(l)]||'rest';const grouped=statusFilter==='all'&&!query;const cards=all.length?(grouped?groups.map(([key,title,sub,symbol])=>{const members=shown.filter(l=>groupKey(l)===key);return members.length?`<section class="lead-group"><h2 class="lead-group-title">${icon(symbol)}${title}${sub?`<span>— ${sub}</span>`:''}<b>${all.filter(l=>groupKey(l)===key).length}</b></h2><div class="cards">${members.map(card).join('')}</div></section>`:''}).join(''):shown.map(card).join('')):'<div class="empty"><h2>No matching leads</h2><p>Try another name, business or filter.</p><button class="btn" data-action="reset-filters">Clear search & filters</button></div>';$('#lead-results').innerHTML=`${selectMode?`<div class="select-line"><label><input type="checkbox" class="selection-check" id="select-all" ${all.length&&all.every(l=>selection.has(l.id))?'checked':''}>Select all ${all.length} results</label><span>${selection.size} selected</span></div>`:''}<div class="cards ${grouped?'grouped-cards':''}">${cards}</div><div class="list-bottom"><span>${all.length?`1–${Math.min(limit,all.length)} of ${all.length}`:'0 leads'}</span>${all.length>limit?'<button class="btn" data-action="more">Show 36 more</button>':''}</div><div id="bulk-area">${bulkHTML()}</div>`;const selectAll=$('#select-all');if(selectAll)selectAll.onchange=()=>{all.forEach(l=>selectAll.checked?selection.add(l.id):selection.delete(l.id));boardResults()};wireSelection();arrangeBulk($('#lead-results'))};

// Date ranges stay provisional until Apply; Cancel preserves the current view.
let rangeDraft=null;
function openDateRange(target){const from=target==='activity'?activityFrom:dateFrom,to=target==='activity'?activityTo:dateTo;rangeDraft={target,from:from||'',to:to||'',month:new Date((from||today())+'T12:00:00')};rangeDraft.month.setDate(1);modal('Choose dates','Select a start date, then an end date.','<div id="range-picker"></div>','<button class="btn" data-action="close">Cancel</button><button class="btn primary" data-range-apply>Apply dates</button>');$('#modal').classList.add('range-modal');drawDateRange()}
function drawDateRange(){const r=rangeDraft;const monthHTML=offset=>{const month=new Date(r.month.getFullYear(),r.month.getMonth()+offset,1),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return `<section class="range-month"><h3>${month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h3><div class="range-grid">${['S','M','T','W','T','F','S'].map(d=>`<span class="range-weekday">${d}</span>`).join('')}${'<span></span>'.repeat(month.getDay())}${Array.from({length:count},(_,i)=>{const key=dateKey(new Date(month.getFullYear(),month.getMonth(),i+1)),edge=key===r.from||key===r.to,inside=r.from&&r.to&&key>r.from&&key<r.to;return `<button data-range-day="${key}" class="${edge?'range-edge':inside?'range-inside':''}" aria-label="${key}" aria-pressed="${!!edge}">${i+1}</button>`}).join('')}</div></section>`};$('#range-picker').innerHTML=`<div class="range-selection" aria-live="polite"><div><span>Start date</span><strong>${r.from||'Choose date'}</strong></div><span>→</span><div><span>End date</span><strong>${r.to||'Choose date'}</strong></div></div><div class="range-navigation"><button class="btn icon-only" data-range-move="-1" aria-label="Previous month">${icon('back')}</button><span>${r.from&&!r.to?'Now choose the end date':'Choose your date range'}</span><button class="btn icon-only" data-range-move="1" aria-label="Next month">${icon('chevron')}</button></div><div class="range-months">${monthHTML(0)}${monthHTML(1)}</div>`;$('[data-range-apply]').disabled=!r.from||!r.to}
const finishAgenda=renderFollowups;renderFollowups=function(){finishAgenda();const tools=$('.follow-tools');if(tools)tools.innerHTML=`<button class="btn agenda-dates" data-agenda-range>${icon('calendar')}${dateFrom?esc(dateFrom===dateTo?dateFrom:dateFrom+' — '+dateTo):'Date range'}</button>${dateFrom?'<button class="btn ghost" data-agenda-reset>Clear dates</button>':''}`;const side=$('.agenda-sidebar');if(side&&!side.querySelector('.agenda-caption'))side.insertAdjacentHTML('afterbegin','<div class="agenda-caption">Your calendar<span>Select a day to see its follow-ups</span></div>');const summary=$('.follow-summary');if(summary)summary.textContent='Times in '+localTZLabel;};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.statusChoice==='Follow-Up'||(b.dataset.action==='save-status'&&$('#status-value')?.value==='Follow-Up')){e.preventDefault();e.stopImmediatePropagation();const note=$('#status-note')?.value||'';schedule([selected]);if(note)$('#follow-note').value=note;return}if(b.hasAttribute('data-agenda-range'))openDateRange('followups');if(b.hasAttribute('data-agenda-reset')){dateFrom='';dateTo='';renderFollowups()}if(b.dataset.rangeMove){rangeDraft.month.setMonth(rangeDraft.month.getMonth()+Number(b.dataset.rangeMove));drawDateRange()}if(b.dataset.rangeDay){const day=b.dataset.rangeDay,r=rangeDraft;if(!r.from||r.to){r.from=day;r.to=''}else{r.to=day;if(r.to<r.from)[r.from,r.to]=[r.to,r.from]}drawDateRange()}if(b.hasAttribute('data-range-apply')&&rangeDraft?.from&&rangeDraft?.to){const r=rangeDraft;close();if(r.target==='activity'){activityFrom=r.from;activityTo=r.to;activityPeriod='custom';activityLimit=50;renderActivity()}else{dateFrom=r.from;dateTo=r.to;followFilter='all';selection.clear();renderFollowups()}}},true);
const rangeAwareModal=modal;modal=function(...args){$('#modal').classList.remove('range-modal');return rangeAwareModal(...args)};

// Back gesture starts only at the screen edge, never in cards, filters or forms.
function edgeBackEligible(x,touches){return touches===1&&x<=24&&innerWidth<=700&&!!currentSession&&!$('#modal').open&&(!!selected||view!=='leads')}
function edgeBackCommit(dx,dy){return dx>=80&&Math.abs(dy)<Math.min(60,dx/2)}
let edgeBack=null;
window.addEventListener('touchstart',e=>{const t=e.touches[0];edgeBack=t&&edgeBackEligible(t.clientX,e.touches.length)?{x:t.clientX,y:t.clientY,locked:false}:null},{passive:true});
window.addEventListener('touchmove',e=>{if(!edgeBack)return;if(e.touches.length!==1){edgeBack=null;return}const t=e.touches[0],dx=t.clientX-edgeBack.x,dy=t.clientY-edgeBack.y;if(!edgeBack.locked&&Math.abs(dy)>20&&Math.abs(dy)>dx){edgeBack=null;return}if(dx>18&&dx>Math.abs(dy)*1.5){edgeBack.locked=true;if(e.cancelable)e.preventDefault();document.body.style.setProperty('--back-progress',Math.min(1,dx/100));document.body.classList.add('edge-back-active')}},{passive:false});
function clearEdgeBack(){edgeBack=null;document.body.classList.remove('edge-back-active');document.body.style.removeProperty('--back-progress')}
window.addEventListener('touchend',e=>{const gesture=edgeBack,t=e.changedTouches[0];clearEdgeBack();if(!gesture?.locked||!t||!edgeBackCommit(t.clientX-gesture.x,t.clientY-gesture.y))return;const back=selected?document.querySelector('[data-action="back"]'):document.querySelector('#mobile-nav [data-view="leads"]');back?.click()},{passive:true});
window.addEventListener('touchcancel',clearEdgeBack,{passive:true});
