'use strict';
let activityPeriod='week',activityFrom='',activityTo='';
function activityBounds(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),end=new Date(start);if(activityPeriod==='today')end.setDate(end.getDate()+1);else if(activityPeriod==='week'||activityPeriod==='last'){start.setDate(start.getDate()-((start.getDay()+6)%7));if(activityPeriod==='last')start.setDate(start.getDate()-7);end.setTime(start.getTime());end.setDate(end.getDate()+7)}else{const s=activityFrom?new Date(activityFrom+'T00:00:00'):null,e=activityTo?new Date(activityTo+'T00:00:00'):null;if(e)e.setDate(e.getDate()+1);return [s?.getTime()||0,e?.getTime()||Infinity]}return [start.getTime(),end.getTime()]}
renderActivity=function(){const filters=[['all','All'],['received','Received'],['opened','Opened'],['call','Calls'],['message','Messages'],['followup','Follow-ups'],['note','Notes'],['status','Status']];$('#main').innerHTML=`<div class="page activity-page"><div class="page-title"><h1>Activity</h1>${noticeButton()}</div><div class="activity-periods" aria-label="Activity date filter">${[['week','Current week'],['today','Today'],['last','Last week']].map(([p,t])=>`<button data-activity-period="${p}" class="${activityPeriod===p?'active':''}" aria-pressed="${activityPeriod===p}">${t}</button>`).join('')}<button data-activity-period="custom" class="${activityPeriod==='custom'?'active':''}" aria-label="Choose activity dates" aria-pressed="${activityPeriod==='custom'}">${icon('calendar')}<span>Dates</span></button></div><p class="activity-range-label" id="activity-range-label"></p>${searchTools()}<div class="filters">${filters.map(([f,t])=>`<button class="filter ${eventFilter===f?'active':''}" data-event-filter="${f}" aria-pressed="${eventFilter===f}">${t}</button>`).join('')}</div><div id="activity-results"></div></div>`;activityResults();wireSearch(activityResults);for(const id of ['activity-from','activity-to']){const el=$('#'+id);if(el)el.onchange=()=>{activityFrom=$('#activity-from').value;activityTo=$('#activity-to').value;activityLimit=50;activityResults()}}};
activityResults=function(){const [start,end]=activityBounds(),invalid=activityPeriod==='custom'&&activityFrom&&activityTo&&activityFrom>activityTo;if($('#activity-date-error'))$('#activity-date-error').textContent=invalid?'End date must be on or after start date.':'';const a=invalid?[]:events().filter(e=>e.at&&e.at>=start&&e.at<end&&(eventFilter==='all'||e.kind===eventFilter)&&byId[e.leadId]&&matches(byId[e.leadId]));$('#activity-range-label').textContent=activityPeriod==='custom'?`${activityFrom||'Any start date'} — ${activityTo||'Any end date'} · ${localTZLabel}`:`${new Date(start).toLocaleDateString('en-US',{month:'short',day:'numeric'})} — ${new Date(end-1).toLocaleDateString('en-US',{month:'short',day:'numeric'})} · ${localTZLabel}`;$('#activity-results').innerHTML=`<div class="activity-paper">${a.length?timeline(a.slice(0,activityLimit)):'<div class="empty" style="border:0"><h2>No activity in this date range</h2><p>Choose another period or event type.</p></div>'}</div><div class="list-bottom"><span>${Math.min(a.length,activityLimit)} of ${a.length} events</span>${a.length>activityLimit?'<button class="btn" data-action="more-activity">Show more</button>':''}</div>`};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.view==='activity'){activityPeriod='week';activityFrom='';activityTo='';eventFilter='all';activityLimit=50}if(b?.dataset.activityPeriod){if(b.dataset.activityPeriod==='custom'){openDateRange('activity');return}activityPeriod=b.dataset.activityPeriod;activityLimit=50;renderActivity()}},true);
const previousCardPolish=card;card=function(l){let html=previousCardPolish(l);const same=String(l.business||'').trim().toLowerCase()===String(l.name||'').trim().toLowerCase();if(same||!l.business)html=html.replace(/<span class="card-business">.*?<\/span>/,'');html=html.replace('class="lead-card ',`class="lead-card ${same||!l.business?'single-identity ':''}`);return html};
function arrangeBulk(root){const area=root?.querySelector('#bulk-area'),line=root?.querySelector('.select-line');if(area&&line&&selection.size)line.after(area)}
const oldBoardPolish=boardResults;boardResults=function(){oldBoardPolish();arrangeBulk($('#lead-results'))};
const oldFollowResultsPolish=followResults;followResults=function(){oldFollowResultsPolish();arrangeBulk($('#follow-results'));document.querySelectorAll('.follow-row:not(.follow-header)').forEach(row=>{const n=row.querySelector('.follow-note');if(n?.textContent.trim()){const text=n.textContent;n.innerHTML=`${icon('edit')}<span>${esc(text)}</span>`}})};
const oldDetailPolish=renderDetail;renderDetail=function(){oldDetailPolish();const must=$('.notes-important .section-label');if(must)must.textContent='Must know';const buttons=$('.research-buttons');if(buttons){const area=document.createElement('section');area.className='research-end side-section';area.innerHTML='<h2 class="section-label">Business research</h2>';area.append(buttons);$('.info-grid').append(area)}document.querySelectorAll('[data-native-contact]').forEach(a=>{if(!byId[selected]?.phone10){a.removeAttribute('href');a.setAttribute('aria-disabled','true');a.title='No contact number in this demo'}})};
// Initial rendering is performed by session.js after all layers are registered.

const leadsFinalPolish=renderLeads;renderLeads=function(){leadsFinalPolish();const banner=$('.fresh-banner strong');if(banner&&arrival?.startsWith('DEMO-'))banner.textContent='New lead'};
function syncFollowFilterState(){const all=document.querySelector('[data-follow-filter="all"]');if(all){all.textContent='All follow-ups';const active=followFilter==='all'&&!dateFrom&&!dateTo;all.classList.toggle('active',active);all.setAttribute('aria-pressed',String(active))}document.querySelector('[data-calendar-clear]')?.remove();document.querySelector('[data-action="clear-dates"]')?.remove()}
const followPageFinal=renderFollowups;renderFollowups=function(){followPageFinal();syncFollowFilterState()};
const followRowsFinal=followResults;followResults=function(){followRowsFinal();syncFollowFilterState()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-follow-filter]');if(b){dateFrom='';dateTo=''}},true);
