'use strict';
Object.assign(paths,{paint:'M4 3h12v7H4z M16 6h4v8h-8v7 M2 5v3',leaf:'M20 3C9 2 2 9 5 16s15 3 15-13ZM5 20 16 9',food:'M4 3v7m4-7v7M2 3v5a4 4 0 0 0 8 0V3M6 12v9M18 3c-5 5-4 9 0 9v9m0-18v9',health:'M9 3h6v6h6v6h-6v6H9v-6H3V9h6z',home:'m3 10 9-7 9 7M5 9v12h14V9M9 21v-7h6v7',store:'M3 9h18l-2-6H5z M4 9v12h16V9M8 21v-7h8v7',dollar:'M12 2v20m6-16C15 2 6 3 6 8s12 3 12 8-9 6-12 2'});
function businessStyle(l){const t=l.type||'';return /paint/i.test(t)?['paint','violet']:/trucking|transport|auto/i.test(t)?['truck','blue']:/landscap|lawn/i.test(t)?['leaf','green']:/food|restaurant|grocery|bak/i.test(t)?['food','orange']:/health|daycare|child/i.test(t)?['health','rose']:/clean|wash/i.test(t)?['spark','cyan']:/contract|carpent|roof|weld|hvac|handyman|mason|electric|plumb/i.test(t)?['tool','amber']:/retail|store|dealer/i.test(t)?['store','orange']:/landlord|property/i.test(t)?['home','blue']:['briefcase','violet']}
function businessIcon(l){const [i,c]=businessStyle(l);return `<span class="business-icon ${c}" title="${esc(l.type||'Business')}">${icon(i)}</span>`}
card=function(l){const t=task(l.id),[i,c]=businessStyle(l);return `<article class="lead-card ${c} ${stage(l)==='New / Transferred'?'new':''} ${selection.has(l.id)?'selected':''} ${arrival===l.id?'fresh-animate':''}" data-card="${esc(l.id)}"><div class="card-header">${businessIcon(l)}<span class="card-id">${esc(l.id)}</span>${selectMode?`<input class="card-select" type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.name)}" ${selection.has(l.id)?'checked':''}>`:badge(stage(l))}</div><button class="card-body" data-open="${esc(l.id)}"><span class="card-name">${esc(l.name)}</span><span class="card-business">${esc(l.business||l.type||'')}</span><span class="card-type">${esc(l.type||'')}</span></button><div class="card-coverages">${(l.coverages||[]).slice(0,2).map(c=>`<span class="cov">${esc(c)}</span>`).join('')}${l.coverages?.length>2?`<span class="cov">+${l.coverages.length-2}</span>`:''}</div><div class="card-footer"><span>${esc(l.state||'')}${l.state?' · ':''}${esc(age(l))}</span>${t?`<span class="follow-time">${icon('calendar')}${esc(dateLabel(t.at))}</span>`:selectMode?badge(stage(l)):`<span class="card-arrow">${icon('arrow')}</span>`}</div></article>`};
const originalDetail=renderDetail;renderDetail=function(){originalDetail();const l=byId[selected];$('.identity').insertAdjacentHTML('afterbegin',`<div class="detail-business-icon">${businessIcon(l)}</div>`);const names={'Contact':'users','Business profile':'briefcase','Financials':'dollar','Coverage answers':'shield','Additional information':'file'};document.querySelectorAll('.info-section h2').forEach(h=>h.innerHTML=icon(names[h.textContent]||'file')+h.innerHTML);document.querySelectorAll('[data-action="status"]').forEach(b=>b.innerHTML=icon('checkcircle')+'Status');};
const originalImported=importedEvents;importedEvents=function(){return [...originalImported(),...ALL.filter(l=>Number(l.calls)>0).map(l=>({id:'call-total-'+l.id,leadId:l.id,kind:'call',at:0,preview:false,text:`${l.calls} recorded call attempt${Number(l.calls)===1?'':'s'} · Historical total`}))]};HISTORY=null;
let calMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),pickerMonth=new Date(calMonth);
function calendarHTML(month,mode){const y=month.getFullYear(),m=month.getMonth(),start=new Date(y,m,1).getDay(),end=new Date(y,m+1,0).getDate(),chosen=mode==='picker'?$('#follow-date')?.value:dateFrom;const counts={};followLeads().forEach(l=>{const t=task(l.id);if(t){const key=dateKey(new Date(t.at));counts[key]=(counts[key]||0)+1}});return `<div class="calendar-head"><strong>${month.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</strong><div><button class="cal-arrow" data-cal-move="-1" data-cal-mode="${mode}" aria-label="Previous month">${icon('back')}</button><button class="cal-arrow" data-cal-move="1" data-cal-mode="${mode}" aria-label="Next month">${icon('chevron')}</button></div></div><div class="calendar-week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-days">${Array.from({length:start},()=>'<span></span>').join('')}${Array.from({length:end},(_,i)=>{const key=dateKey(new Date(y,m,i+1));return `<button class="cal-day ${key===today()?'is-today':''} ${key===chosen?'is-selected':''}" data-cal-date="${key}" data-cal-mode="${mode}" aria-label="${key}${counts[key]?', '+counts[key]+' follow-ups':''}" aria-pressed="${key===chosen}"><span>${i+1}</span>${counts[key]?`<i>${mode==='agenda'?counts[key]:''}</i>`:''}</button>`}).join('')}</div>`}
function refreshCalendar(){if($('#agenda-calendar'))$('#agenda-calendar').innerHTML=calendarHTML(calMonth,'agenda');if($('#picker-calendar'))$('#picker-calendar').innerHTML=calendarHTML(pickerMonth,'picker')}
const oldFollowRender=renderFollowups;renderFollowups=function(){oldFollowRender();const page=$('#main .page');page.classList.add('follow-page');const wrap=document.createElement('div');wrap.className='agenda-layout';const side=document.createElement('aside');side.className='agenda-sidebar';side.innerHTML=`<div class="calendar-card" id="agenda-calendar">${calendarHTML(calMonth,'agenda')}</div><button class="btn calendar-clear" data-calendar-clear>All dates</button>`;const list=document.createElement('section');list.className='agenda-list';['.search','.filters','.follow-tools','.follow-summary','#follow-results'].forEach(sel=>{const el=page.querySelector(sel);if(el){const parent=el.classList.contains('search')?el.parentElement:el;list.append(parent)}});wrap.append(side,list);page.append(wrap);for(const id of ['date-from','date-to']){const el=$('#'+id),old=el.onchange;el.onchange=e=>{old(e);refreshCalendar()}}};
const oldSchedule=schedule;schedule=function(ids){oldSchedule(ids);if(!$('#follow-date'))return;pickerMonth=new Date($('#follow-date').value+'T12:00:00');pickerMonth.setDate(1);$('#modal').classList.add('schedule-modal');$('.quick-dates').insertAdjacentHTML('afterend','<div id="picker-calendar" class="picker-calendar"></div>');refreshCalendar();$('#follow-date').onchange=()=>{const d=new Date($('#follow-date').value+'T12:00:00');if(!isNaN(d)){pickerMonth=new Date(d.getFullYear(),d.getMonth(),1);refreshCalendar()}};};
const oldModal=modal;modal=function(...args){$('#modal').classList.remove('schedule-modal','status-modal');oldModal(...args)};
statusModal=function(preset){modalIds=[selected];const l=byId[selected];const current=preset||stage(l),values=['Contacted','Not Reached','Follow-Up','Quoted','Bound / Sold','Declined','Dead / Lost'];const syms=['message','phone','calendar','file','checkcircle','close','flag'];modal('Update status',`${l.name} · ${l.id}`,`<input type="hidden" id="status-value" value="${esc(current)}"><div class="status-options">${values.map((s,i)=>`<button class="status-option ${s===current?'chosen':''}" data-status-choice="${s}" aria-pressed="${s===current}"><span class="status-symbol s${i}">${icon(syms[i])}</span><span>${label(s)}</span><span class="status-radio">${icon('check')}</span></button>`).join('')}</div><div id="status-fields"></div><label class="form-field note-field">Note <span class="optional">· optional</span><textarea id="status-note" placeholder="Add a note…"></textarea></label><p class="helper">Only saved in this preview.</p><p class="error" id="form-error" role="alert"></p>`,`<button class="btn" data-action="close">Cancel</button><button class="btn primary" data-action="save-status">${icon('check')}Save status</button>`);$('#modal').classList.add('status-modal');statusFields()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.statusChoice){$('#status-value').value=b.dataset.statusChoice;document.querySelectorAll('[data-status-choice]').forEach(x=>{x.classList.toggle('chosen',x===b);x.setAttribute('aria-pressed',String(x===b))});statusFields()}if(b.dataset.calMove){const d=b.dataset.calMode==='picker'?pickerMonth:calMonth;d.setMonth(d.getMonth()+Number(b.dataset.calMove));refreshCalendar()}if(b.dataset.calDate){if(b.dataset.calMode==='picker'){$('#follow-date').value=b.dataset.calDate;refreshCalendar()}else{dateFrom=b.dataset.calDate;dateTo=dateFrom;followFilter='all';selection.clear();renderFollowups()}}if(b.hasAttribute('data-calendar-clear')){dateFrom='';dateTo='';followFilter='all';renderFollowups()}if(b.dataset.day!==undefined){pickerMonth=new Date($('#follow-date').value+'T12:00:00');pickerMonth.setDate(1);refreshCalendar()}});
// Initial rendering is performed by session.js after all layers are registered.

const priorActivity=renderActivity;renderActivity=function(){priorActivity();if(eventFilter==='call')$('#activity-results').insertAdjacentHTML('beforebegin','<p class="call-explainer">Historical counts are grouped by client. Individual call dates and outcomes were not included in the saved data.</p>')};
