'use strict';
const IS_LOCAL_PREVIEW=false;
const ACCOUNT_PREVIEWS={};
const SESSION_KEY='lm-crm-session'+(location.search.includes('qa')?'-qa':'');
let currentSession=IS_LOCAL_PREVIEW?{...ACCOUNT_PREVIEWS.k,role:'agent',preview:true}:null;
let activeAgent='k',authEmail='',authStep='email';
let requestedLead=new URLSearchParams(location.search).get('lead')||new URLSearchParams(location.search).get('id');
{const url=new URL(location.href);['t','s','adm','session','code'].forEach(key=>url.searchParams.delete(key));history.replaceState(null,'',url.pathname+url.search+url.hash)}
const snapshotLeads=ALL.slice();
const emptyOverlay=()=>({tasks:{},events:[],drafts:{},statuses:{},dismissed:{},opened:{},noticeRead:{}});
function isReadOnly(){return currentSession?.role==='admin'}
function currentAccount(){return IS_LOCAL_PREVIEW?ACCOUNT_PREVIEWS[activeAgent]:currentSession?.accounts?.find(a=>a.agent===activeAgent)||currentSession}
function applySessionUI(){document.body.classList.toggle('admin-readonly',isReadOnly());const account=currentAccount();if(account){AGENT_NAME=account.smsName||account.name;const sb=$('.sidebar-bottom');if(sb)sb.innerHTML=`<span class="initials">${esc(account.name.slice(0,1))}</span><span>${esc(account.name)}</span><button class="sidebar-signout" data-signout aria-label="Sign out" title="Sign out">${icon('logout')}</button>`;document.title='Leads · '+account.name}if(isReadOnly()){const target=$('.page')||$('.detail-body');if(target&&!target.querySelector('.admin-banner'))target.insertAdjacentHTML('afterbegin',`<div class="admin-banner">${icon('shield')}<span>Admin · Read-only</span><button data-switch-agent>${esc(account?.name||'Choose agent')} ${icon('chevron')}</button></div>`);document.querySelectorAll('[data-action="save-note"],[data-action="save-status"],[data-action="save-follow"],[data-action="complete-one"],[data-action="bulk-complete"],[data-preview-contact],[data-native-contact]').forEach(b=>{b.setAttribute('aria-disabled','true');b.title='Read-only admin view';if(b.tagName==='A')b.removeAttribute('href');else b.disabled=true});const draft=$('#note-draft');if(draft){draft.oninput=null;draft.readOnly=true;draft.placeholder='Read-only admin view';draft.value=''}if($('#modal').open&&!$('#modal .admin-caption'))$('#modal .modal-body')?.insertAdjacentHTML('afterbegin','<p class="admin-caption">Read-only access · Changes cannot be saved.</p>')}if(IS_LOCAL_PREVIEW&&activeAgent!=='k'){const empty=$('.empty p');if(empty)empty.textContent=`${account?.name||'This agent'}’s records will load after secure sign-in in the connected version. This local review contains only Kateryna’s snapshot.`}}
const sessionCanSave=canSave;canSave=function(){if(!currentSession||isReadOnly()){toast('Read-only admin view. No changes were made.');return false}return sessionCanSave()};
const sessionModal=modal;modal=function(...args){sessionModal(...args);applySessionUI()};
const sessionOpenLead=openLead;openLead=function(id){if(isReadOnly()){oldOpenV4(id);return}sessionOpenLead(id)};
const sessionContactEvent=contactEvent;contactEvent=function(...args){if(!isReadOnly()&&currentSession)sessionContactEvent(...args)};
const sessionAddEvent=addEvent;addEvent=function(...args){if(!isReadOnly()&&currentSession)sessionAddEvent(...args)};
function showAuth(step='email',error=''){authStep=step;document.title='Sign in · Lead Manager';document.body.classList.add('signed-out');$('#dock').innerHTML='';$('#modal').open&&close();let screen=$('#auth-screen');if(!screen){screen=document.createElement('section');screen.id='auth-screen';screen.className='auth-screen';document.body.append(screen)}screen.hidden=false;screen.innerHTML=`<div class="auth-card"><div class="auth-logo"><img src="favicon.svg" alt="">Lead Manager</div><h1>${step==='email'?'Welcome back.':'Check your email.'}</h1><p>${step==='email'?'Your leads, conversations and follow-ups. One place.':`If <strong>${esc(authEmail)}</strong> has access, check its inbox for a 6-digit code.`}</p><form id="auth-form">${step==='email'?`<label>Email address<input id="auth-email" type="email" name="username" autocomplete="username" autocapitalize="none" spellcheck="false" required placeholder="you@example.com" value="${esc(authEmail)}"></label>`:`<label>Access code<input id="auth-code" class="otp-input" type="text" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required aria-describedby="auth-code-help"></label><span id="auth-code-help" class="helper">Expires in 10 minutes.</span>`}<p class="auth-error" role="alert">${esc(error)}</p><button class="btn primary" type="submit">${step==='email'?'Send access code':'Sign in'}</button>${step==='email'?'<button type="button" class="auth-back" data-existing-code>Already have a code?</button>':''}${step==='code'?'<button type="button" class="auth-back" data-auth-back>Use another email</button><button type="button" class="auth-back" data-auth-resend>Resend code</button>':''}</form><p class="auth-footnote">${IS_LOCAL_PREVIEW?'':'A private access code. No password to remember.'}</p></div>`;$('#auth-form').onsubmit=submitAuth;screen.querySelector('[data-existing-code]')?.addEventListener('click',()=>{const input=$('#auth-email');if(!input.reportValidity())return;authEmail=input.value.trim().toLowerCase();showAuth('code')});screen.querySelector('[data-auth-back]')?.addEventListener('click',()=>showAuth());screen.querySelector('[data-auth-resend]')?.addEventListener('click',async e=>{e.target.disabled=true;try{await requestCode(authEmail);toast(IS_LOCAL_PREVIEW?'':'If this email has access, a new code is on its way.')}catch(err){screen.querySelector('.auth-error').textContent=err.message}finally{e.target.disabled=false}})}
// GitHub Pages uses a credential-free CORS request to Apps Script. The bearer
// token stays in this tab's session storage, never in URLs or persistent storage.
const CRM_API_URL='https://script.google.com/macros/s/AKfycbw3vDEX509WAsvwrT6exgib4z4tFknocNAr82uxvDrR2u9NYRMyLM7aOqJWrNERCqSZ/exec?api=crm';
const ACCESS_STORAGE_NAME='lm-crm-access';
const REMEMBERED_ACCESS='lm-crm-remembered-access';
function clearAccess(){for(const [storage,key]of [[localStorage,REMEMBERED_ACCESS],[sessionStorage,ACCESS_STORAGE_NAME]])try{storage.removeItem(key)}catch{}}
function rememberAccess(token){const record=JSON.stringify({token,expiresAt:Date.now()+30*86400000});try{localStorage.setItem(REMEMBERED_ACCESS,record);sessionStorage.removeItem(ACCESS_STORAGE_NAME)}catch{try{sessionStorage.setItem(ACCESS_STORAGE_NAME,token)}catch{}}}
function readAccess(){try{const r=JSON.parse(localStorage.getItem(REMEMBERED_ACCESS)||'null');if(r&&typeof r.token==='string'&&r.expiresAt>Date.now())return r.token;if(r)localStorage.removeItem(REMEMBERED_ACCESS)}catch{}try{const token=sessionStorage.getItem(ACCESS_STORAGE_NAME);if(token){rememberAccess(token);return token}}catch{}return ''}
function pendingCode(){try{const p=JSON.parse(localStorage.getItem('lm-crm-pending-code')||'null');return p&&p.until>Date.now()?p:null}catch{return null}}
function rememberCode(email){try{localStorage.setItem('lm-crm-pending-code',JSON.stringify({email,until:Date.now()+600000,sentAt:Date.now()}))}catch{}}
function forgetCode(){try{localStorage.removeItem('lm-crm-pending-code')}catch{}}
function restoreAuth(){const p=pendingCode();if(p){authEmail=p.email;showAuth('code')}else showAuth()}
function showSessionRetry(){document.body.classList.add('signed-out');let screen=$('#auth-screen');if(!screen){screen=document.createElement('section');screen.id='auth-screen';screen.className='auth-screen';document.body.append(screen)}screen.hidden=false;screen.innerHTML='<div class="auth-card"><div class="auth-logo"><img src="favicon.svg" alt="">Lead Manager</div><h1>Let’s reconnect.</h1><p>Your sign-in is saved. Check your connection and try again.</p><button class="btn primary" data-session-retry>Try again</button></div>';screen.querySelector('[data-session-retry]').onclick=bootSession}

async function crmRequest(action,payload={}){const direct=CRM_API_URL.startsWith('https://'),body={action,...payload};if(direct)body.session=readAccess();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),60000);try{const response=await fetch(CRM_API_URL,{method:'POST',headers:{'Content-Type':direct?'text/plain;charset=UTF-8':'application/json'},cache:'no-store',credentials:direct?'omit':'same-origin',redirect:'follow',signal:controller.signal,body:JSON.stringify(body)});if(response.status===401)expireSession();if(!response.ok)throw new Error(response.status===401?'Your session expired. Sign in again.':'Unable to connect. Please try again.');const result=await response.json();if(result.unauthorized){clearAccess();expireSession()}if(!result.ok)throw new Error(result.error||'Unable to complete this request.');if(direct&&action==='verify_code'&&result.session){rememberAccess(result.session);forgetCode();delete result.session}if(action==='logout'){clearAccess();forgetCode()};return result}catch(err){if(err.name==='AbortError')throw new Error('The connection took too long. Please try again.');throw err}finally{clearTimeout(timer)}}
async function requestCode(email){const p=pendingCode();if(p?.email===email&&Date.now()-p.sentAt<60000)throw new Error('A code was just requested. Check your inbox or wait a minute before resending.');const result=IS_LOCAL_PREVIEW?{ok:true}:await crmRequest('request_code',{email});rememberCode(email);return result}
async function submitAuth(e){e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');button.disabled=true;try{if(authStep==='email'){authEmail=$('#auth-email').value.trim().toLowerCase();await requestCode(authEmail);showAuth('code')}else{let result;result=(await crmRequest('verify_code',{email:authEmail,code:$('#auth-code').value})).principal;await enterSession(result)}}catch(err){if(authStep==='email'&&/Too many code requests/.test(err.message))showAuth('code','Too many requests. Use a recent code if it is still valid, or wait up to an hour before requesting another.');else $('#auth-screen .auth-error').textContent=err.message}finally{button.disabled=false}}
async function enterSession(principal){currentSession=principal;activeAgent=principal.agent||'k';if(IS_LOCAL_PREVIEW){sessionStorage.setItem(SESSION_KEY,JSON.stringify(principal));await switchAgent(activeAgent)}else await loadConnectedAccount(activeAgent);document.body.classList.remove('signed-out');if($('#auth-screen'))$('#auth-screen').hidden=true;render();if(requestedLead){const id=requestedLead;requestedLead=null;if(isReadOnly()){const agent=/^K/.test(id)?'k':/^H/.test(id)?'h':'j';if(agent!==activeAgent)await switchAgent(agent)}if(byId[id])openLead(id);else toast('This lead is not available in your account.')}}
async function switchAgent(agent){if(!['k','j','h'].includes(agent))return;if(!isReadOnly()&&agent!==currentSession.agent)return;activeAgent=agent;selected=null;query='';selection.clear();selectMode=false;view='leads';statusFilter='all';arrival=null;if(IS_LOCAL_PREVIEW){ALL.splice(0,ALL.length,...(agent==='k'?snapshotLeads:[]));Object.keys(byId).forEach(k=>delete byId[k]);ALL.forEach(l=>byId[l.id]=l);local=emptyOverlay();if(agent==='k')try{local=JSON.parse(localStorage.getItem(KEY)||'null')||emptyOverlay()}catch{}HISTORY=null;render()}else await loadConnectedAccount(agent)}
function expireSession(){clearAccess();connectedEpoch++;detailSequence++;connectedHistory=[];connectedBusy=false;currentSession=null;selected=null;selection.clear();local=emptyOverlay();ALL.splice(0);Object.keys(byId).forEach(id=>delete byId[id]);HISTORY=null;$('#main').innerHTML='';$('#sidebar').innerHTML='';showAuth();}
async function signOut(){if(!IS_LOCAL_PREVIEW)await crmRequest('logout');sessionStorage.removeItem(SESSION_KEY);connectedEpoch++;detailSequence++;connectedHistory=[];connectedBusy=false;currentSession=null;selected=null;selection.clear();local=emptyOverlay();ALL.splice(0);Object.keys(byId).forEach(id=>delete byId[id]);HISTORY=null;$('#main').innerHTML='';$('#sidebar').innerHTML='';authEmail='';showAuth()}
const readonlyActions=new Set(['save-note','save-status','save-follow','complete-one','bulk-complete','simulate-call','simulate-message']);
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(isReadOnly()&&(readonlyActions.has(b.dataset.action)||b.hasAttribute('data-preview-contact')||b.hasAttribute('data-native-contact'))){e.preventDefault();e.stopImmediatePropagation();toast('Read-only admin view. No changes were made.');return}if(isReadOnly()&&b.dataset.noticeOpen){e.preventDefault();e.stopImmediatePropagation();close();openLead(b.dataset.noticeOpen);return}if(b.hasAttribute('data-signout'))modal(`${currentSession?.name||'You'}, are you sure you want to sign out?`,'', '<p class="helper">You can sign back in with a new access code.</p>','<button class="btn" data-action="close">Stay signed in</button><button class="btn primary" data-confirm-signout>Sign out</button>');if(b.hasAttribute('data-confirm-signout')){b.disabled=true;signOut().catch(err=>{toast(err.message);b.disabled=false})}if(b.hasAttribute('data-switch-agent')&&isReadOnly())modal('View an agent','Read-only admin view',`<div class="sort-options">${(IS_LOCAL_PREVIEW?['k','j','h'].map(a=>ACCOUNT_PREVIEWS[a]):currentSession.accounts).map(a=>`<button data-agent-choice="${a.agent}" aria-pressed="${activeAgent===a.agent}">${icon('shield')}<span>${esc(a.name)}</span></button>`).join('')}</div>`,'<button class="btn" data-action="close">Cancel</button>');if(b.dataset.agentChoice&&isReadOnly()){close();switchAgent(b.dataset.agentChoice).catch(err=>toast(err.message))}},true);
// Guards protect all persistence paths, including note drafts and notification acknowledgements.
const persistSession=persist;persist=function(){if(!currentSession||isReadOnly()||!IS_LOCAL_PREVIEW)return;persistSession()};
function bootSession(){
if(IS_LOCAL_PREVIEW){try{const stored=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(stored)currentSession=stored}catch{}if(new URLSearchParams(location.search).has('login'))showAuth();else enterSession(currentSession)}else{if(CRM_API_URL.startsWith('https://')&&!readAccess()){restoreAuth();return}document.body.classList.add('signed-out');crmRequest('session').then(r=>enterSession(r.principal)).catch(()=>readAccess()?showSessionRetry():restoreAuth())}

}
