'use strict';
let AGENT_NAME='';
Object.assign(paths,{child:'M12 3a3 3 0 1 1 0 6 3 3 0 0 1 0-6M5 11l7 2 7-2M12 13v4m0 0-5 5m5-5 5 5',beauty:'M12 21c-5-2-9-7-8-12 4 0 7 3 8 6 1-3 4-6 8-6 1 5-3 10-8 12ZM12 15c-4-3-4-8 0-13 4 5 4 10 0 13',education:'m2 9 10-5 10 5-10 5-10-5m4 2v6c4 3 8 3 12 0v-6m4-2v8',camera:'M3 7h4l2-3h6l2 3h4v14H3z M16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0',shirt:'m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0',factory:'M3 21V9l6 4V9l6 4V3h5v18H3m3-4h2m3 0h2m3 0h2',heart:'M12 21 3 12C-3 3 8-2 12 6c4-8 15-3 9 6z',scissors:'M8 8 20 20M8 16 20 4M9 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0M9 18a3 3 0 1 1-6 0 3 3 0 0 1 6 0',whatsapp:'M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.3-4.8A8.5 8.5 0 1 1 20.5 11.6ZM8 7.3c.2-.5.6-.5.9-.5l1 2.3-.8 1c.8 1.8 2 2.9 3.8 3.7l1-1 2.3 1c0 .6-.2 1.3-.8 1.6-1 .5-2.7.1-4.5-1-2-1.2-3.4-3-4-4.6-.4-1.2-.4-1.9.1-2.5'});
const fallbackBusiness=businessStyle;businessStyle=function(l){const t=l.type||'';if(/daycare|childcare/i.test(t))return ['child','rose'];if(/education|tutor/i.test(t))return ['education','blue'];if(/beauty|barber|salon/i.test(t))return ['scissors','rose'];if(/spa|wellness|massage/i.test(t))return ['beauty','rose'];if(/photo|video/i.test(t))return ['camera','violet'];if(/clothing|apparel/i.test(t))return ['shirt','violet'];if(/manufactur/i.test(t))return ['factory','amber'];if(/nonprofit|church/i.test(t))return ['heart','rose'];if(/courier|delivery|towing/i.test(t))return ['truck','blue'];if(/tree/i.test(t))return ['leaf','green'];if(/floor|drywall|plumb/i.test(t))return ['tool','amber'];return fallbackBusiness(l)};
function exactDate(ts){return ts?new Date(ts).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Date unavailable'}
function lastActivity(l){const preview=local.events.filter(e=>e.leadId===l.id&&e.at&&!['received-demo'].includes(e.kind)).map(e=>e.at);return Math.max(l.updated_ts||0,l.opened_ts||0,l.sent_ts||0,...(l.jenny?.notes||[]).map(n=>legacyNoteTime(n,l)),...preview)}
function elapsed(ts){const min=Math.max(0,Math.floor((Date.now()-ts)/60000));return min<1?'Just now':min<60?min+'m':min<1440?Math.floor(min/60)+'h '+min%60+'m':Math.floor(min/1440)+'d '+Math.floor(min%1440/60)+'h'}
card=function(l){const t=task(l.id),[i,c]=businessStyle(l),ts=lastActivity(l);return `<article class="lead-card ${c} ${stage(l)==='New / Transferred'?'new':''} ${selection.has(l.id)?'selected':''} ${arrival===l.id?'fresh-animate':''}" data-card="${esc(l.id)}"><div class="card-header">${businessIcon(l)}<span class="card-id">${esc(l.id)}</span>${selectMode?`<input class="card-select" type="checkbox" data-select="${esc(l.id)}" aria-label="Select ${esc(l.name)}" ${selection.has(l.id)?'checked':''}>`:badge(stage(l))}</div><button class="card-body" data-open="${esc(l.id)}"><span class="card-name">${esc(l.name)}</span><span class="card-business">${esc(l.business||'')}</span><span class="card-type">${esc(l.type||'Business')}${l.state?' · '+esc(l.state):''}</span></button><div class="card-coverages">${(l.coverages||[]).slice(0,2).map(c=>`<span class="cov">${esc(c)}</span>`).join('')}${l.coverages?.length>2?`<span class="cov">+${l.coverages.length-2}</span>`:''}</div><div class="card-footer"><span class="sent-stamp" title="Received · ${esc(exactDate(l.sent_ts))}"><b>${esc(l.id)}</b> · ${esc(exactDate(l.sent_ts))}</span><span class="activity-age" title="Since last activity · ${esc(exactDate(ts))}" aria-label="Since last activity ${esc(elapsed(ts))}">${icon('clock')}<span data-elapsed="${ts}">${elapsed(ts)}</span></span>${t?`<span class="follow-time" title="Follow-up">${icon('calendar')}${esc(dateLabel(t.at))}</span>`:''}</div></article>`};
const previousFiltered=filtered;filtered=function(){const a=previousFiltered();if(statusFilter==='all'&&!query){const rank=l=>({'New / Transferred':0,Opened:1,Called:2})[stage(l)]??3;return a.sort((a,b)=>rank(a)-rank(b)||(sort==='newest'?lastActivity(b)-lastActivity(a):0))}return a};
const ungroupedResults=boardResults;boardResults=function(){ungroupedResults();if(statusFilter!=='all'||query)return;const container=$('#lead-results .cards');if(!container||!container.querySelector('.lead-card'))return;const shown=filtered().slice(0,limit);const groups=[['New / Transferred','New','Opportunity','bolt'],['Opened','Opened','Needs action','file'],['Called','Called','Status pending','phone'],['rest','Everything else','','grid']];container.classList.add('grouped-cards');container.innerHTML=groups.map(([s,title,sub,ico])=>{const a=shown.filter(l=>s==='rest'?!['New / Transferred','Opened','Called'].includes(stage(l)):stage(l)===s);if(!a.length)return '';return `<section class="lead-group"><h2 class="lead-group-title">${icon(ico)}${title}${sub?`<span>— ${sub}</span>`:''}<b>${filtered().filter(l=>s==='rest'?!['New / Transferred','Opened','Called'].includes(stage(l)):stage(l)===s).length}</b></h2><div class="cards">${a.map(card).join('')}</div></section>`}).join('');wireSelection()};
Object.assign(eventLabels,{received:'Received',opened:'Opened',call:'Called',message:'Text app opened'});Object.assign(eventIcons,{received:'bell',opened:'file'});
function legacyNoteTime(text,l){const m=String(text).match(/^(\d{1,2})\/(\d{1,2})\s+(\d{1,2}):(\d{2})\s*(AM|PM)/i);if(!m||+m[1]<1||+m[1]>12||+m[2]<1||+m[2]>31||+m[3]<1||+m[3]>12||+m[4]>59)return 0;const captured=new Date(raw.capturedAt).getTime(),reference=new Date(Number.isFinite(captured)?captured:Date.now());let year=reference.getFullYear();if(+m[1]>reference.getMonth()+1)year--;const h=+m[3]%12+(m[5].toUpperCase()==='PM'?12:0),wanted=Date.UTC(year,+m[1]-1,+m[2],h,+m[4]);if(new Date(wanted).getUTCMonth()!==+m[1]-1)return 0;let ts=wanted;try{for(let i=0;i<3;i++){if(!Number.isFinite(ts))return 0;const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'numeric',hourCycle:'h23'}).formatToParts(new Date(ts)).map(x=>[x.type,x.value]));ts+=wanted-Date.UTC(+p.year,+p.month-1,+p.day,(+p.hour)%24,+p.minute)}return Number.isFinite(ts)?ts:0}catch{return 0}}
importedEvents=function(){return ALL.flatMap(l=>{const a=[];if(l.sent_ts)a.push({id:'received-'+l.id,leadId:l.id,kind:'received',at:l.sent_ts,text:'Lead received'});if(l.opened_ts)a.push({id:'opened-'+l.id,leadId:l.id,kind:'opened',at:l.opened_ts,text:'Lead opened'});if(l.updated_ts&&l.updated_ts>=(l.sent_ts||0)&&!['New / Transferred','Opened'].includes(l.status))a.push({id:'updated-'+l.id,leadId:l.id,kind:l.status==='Called'?'call':'status',at:l.updated_ts,text:l.status==='Called'?'Called · Recorded status change':`Status: ${label(l.status)} · Last recorded update`});(l.jenny?.notes||[]).forEach((text,i)=>a.push({id:`history-${l.id}-${i}`,leadId:l.id,kind:/sms|whatsapp/i.test(text)?'message':/follow.?up/i.test(text)?'followup':'note',at:legacyNoteTime(text,l),text,legacy:true}));return a})};HISTORY=null;
events=function(){HISTORY||=importedEvents();return [...local.events,...HISTORY].sort((a,b)=>(b.at||0)-(a.at||0))};
timeline=function(a,within=false){const dated=a.filter(e=>e.at),undated=a.filter(e=>!e.at);const draw=e=>{const l=byId[e.leadId];return `<li class="activity-item ${e.kind}"><span class="event-icon">${icon(e.iconKey||eventIcons[e.kind]||'file')}</span><div class="event-content"><div class="event-top"><span class="event-title">${e.legacy&&e.kind==='message'?'SMS recorded':e.channel==='whatsapp'?'WhatsApp opened':eventLabels[e.kind]||'Activity'}${e.preview?' · Preview':''}</span><time class="event-time" datetime="${e.at?new Date(e.at).toISOString():''}">${e.at?esc(exactDate(e.at)):'Date unavailable'}</time></div>${within?'':`<button class="event-lead" data-open="${l.id}">${esc(l.name)} <span class="muted small">· ${l.id}</span></button><p class="event-business">${esc(l.business)}</p>`}<p class="event-text">${esc(e.legacy?String(e.text).replace(/^\d{1,2}\/\d{1,2}\s+\d{1,2}:\d{2}\s*(?:AM|PM)\s*[—–-]?\s*/i,''):e.text)}</p></div></li>`};return `<ol class="timeline chronological">${dated.map(draw).join('')||'<li class="timeline-empty">No dated activity yet</li>'}</ol>${undated.length?'<div class="undated-label">Other saved notes · Date unavailable</div><ol class="timeline">'+undated.map(draw).join('')+'</ol>':''}`};
function undatedCalls(l){return Math.max(0,Number(l.calls||0)-(l.status==='Called'&&l.updated_ts>=l.sent_ts?1:0))}
function callArchive(l){const n=undatedCalls(l);return n?`<div class="call-archive">${icon('phone')}<span><strong>${n} earlier call attempt${n===1?'':'s'}</strong><small>Dates for these earlier calls are not available in this preview.</small></span></div>`:''}

const workflowActivity=renderActivity;renderActivity=function(){workflowActivity();$('.page-title').insertAdjacentHTML('beforeend',noticeButton());const old=$('.call-explainer');if(old)old.remove();if(eventFilter==='call'){const a=ALL.filter(l=>undatedCalls(l)>0&&matches(l));$('#activity-results').insertAdjacentHTML('beforeend',`<section class="historical-calls"><h2>Earlier calls <span>Dates not imported</span></h2>${a.map(l=>`<button class="archive-row" data-open="${l.id}"><span>${esc(l.name)}<small>${l.id} · ${esc(l.business)}</small></span><strong>${undatedCalls(l)}</strong>${icon('chevron')}</button>`).join('')}</section>`)}};
const oldInfoGroups=infoGroups;infoGroups=function(l){return oldInfoGroups({...l,phone10:'',details:(l.details||[]).filter(x=>!/phone|tel[eé]fono|mobile|fax/i.test(x[0]))})};
function smsCountFor(l){return Math.max(Number(l.sms)||0,(l.jenny?.notes||[]).filter(x=>/SMS sent/i.test(x)).length)+local.events.filter(e=>e.leadId===l.id&&e.kind==='message'&&e.channel==='text').length}
function smsText(l){const first=String(l.name||'').trim().split(/\s+/)[0],linea=l.coverages?.[0]||'seguro comercial';return smsCountFor(l)?`${first}, soy ${AGENT_NAME} otra vez. Le volví a llamar por su cotización de ${linea} y no tuve éxito. Espero su respuesta, feliz de asistirle!`:`Hola ${first}, soy ${AGENT_NAME}, su agente asignada para su cotización de ${linea}. La estoy trabajando en este momento y me faltan unos datos por confirmar para enviársela. A qué hora le puedo llamar?`}
function nativeHref(l,channel){const phone='+1'+String(l.phone10||'').replace(/\D/g,'');return channel==='call'?'tel:'+phone:channel==='whatsapp'?'https://wa.me/'+phone.slice(1)+'?text='+encodeURIComponent(smsText(l)):'sms:'+phone+(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'&':'?')+'body='+encodeURIComponent(smsText(l))}
function contactEvent(l,channel){const text=channel==='call'?'Phone app opened · Call requested':channel==='text'?'Messages opened with a prefilled SMS. Delivery is not confirmed.':'WhatsApp opened with a prefilled message. Delivery is not confirmed.';local.events.unshift({id:crypto.randomUUID(),leadId:l.id,kind:channel==='call'?'call':'message',channel,text,at:Date.now(),preview:true});if(channel==='call'&&['New / Transferred','Opened'].includes(stage(l)))local.statuses[l.id]='Called';persist()}
contact=function(channel){const l=byId[selected];if(!l?.phone10){toast('No contact number is available for this lead.');return}modal(channel==='call'?'Call preview':channel==='text'?'Text preview':'WhatsApp preview',l.name,`<p class="helper">On iPhone, this button opens ${channel==='call'?'Phone':channel==='text'?'Messages':'WhatsApp'} directly.</p>${channel==='call'?'':`<div class="sms-preview" lang="es">${esc(smsText(l))}</div>`}<p class="helper">Desktop preview · Nothing is sent.</p>`,`<button class="btn" data-action="close">Close</button><button class="btn primary" data-preview-contact="${channel}">Simulate app opening</button>`)};
const originalNavV4=nav;nav=function(){originalNavV4();$('.sidebar-bottom').innerHTML='<span class="initials">KH</span><span>'+AGENT_NAME+'</span>'};
let noticeTab='leads';local.opened||={};local.noticeRead||={};
function unreadLeads(){return ALL.filter(l=>(l.status==='New / Transferred'&&!l.opened_ts&&!local.opened?.[l.id])||(arrival===l.id&&!local.noticeRead?.['arrival-'+l.id]))}
function dueNotices(){return followLeads().filter(l=>{const t=task(l.id);return t&&dateKey(new Date(t.at))<=today()&&local.noticeRead?.['follow-'+l.id]!==today()})}
function noticeButton(){const n=unreadLeads().length+dueNotices().length;return `<button class="notification-bell ${n?'has-unread':''}" data-notifications aria-label="Notifications${n?', '+n+' unread':''}">${icon('bell')}${n?`<span>${n}</span>`:''}</button>`}
function updateBells(){document.querySelectorAll('.notification-bell:not(.signout-button)').forEach(b=>{const html=noticeButton();if(b.outerHTML!==html)b.outerHTML=html})}
function noticeModal(){const a=noticeTab==='leads'?unreadLeads():dueNotices();modal('Notifications','',`<div class="notification-tabs"><button data-notice-tab="leads" class="${noticeTab==='leads'?'active':''}">New leads <b>${unreadLeads().length}</b></button><button data-notice-tab="follow" class="${noticeTab==='follow'?'active':''}">Follow-ups <b>${dueNotices().length}</b></button></div><div class="notice-list">${a.length?a.map(l=>`<button class="notice-row" data-notice-open="${l.id}">${businessIcon(l)}<span><strong>${esc(l.name)}</strong><small>${l.id} · ${esc(l.business)}</small><em>${noticeTab==='leads'?'Received · '+esc(exactDate(l.sent_ts)):'Follow-up · '+esc(exactDate(task(l.id).at))}</em></span>${icon('chevron')}</button>`).join(''):`<div class="notice-empty">${icon('checkcircle')}<h3>${noticeTab==='leads'?'All leads opened':'No follow-ups due'}</h3><p>${noticeTab==='leads'?'New arrivals stay here until you open them.':'Daily reminders appear here on the scheduled day.'}</p></div>`}</div>`,'<button class="btn" data-action="close">Close</button>');$('#modal').classList.add('notifications-modal')}
const oldModalV4=modal;modal=function(...args){$('#modal').classList.remove('notifications-modal');oldModalV4(...args)};
const oldOpenV4=openLead;openLead=function(id){if(!byId[id])return;const l=byId[id];if(!l.opened_ts&&!local.opened[id]){local.opened[id]=Date.now();addEvent(id,'opened','Lead opened');if(stage(l)==='New / Transferred')local.statuses[id]='Opened'}if(arrival===id){local.noticeRead['arrival-'+id]=true;arrival=null}persist();oldOpenV4(id)};
const detailV4=renderDetail;renderDetail=function(){detailV4();$('.phone-label')?.remove();$('.head-nav').insertAdjacentHTML('afterbegin',noticeButton());document.querySelectorAll('[data-contact]').forEach(b=>{const c=b.dataset.contact,a=document.createElement('a');a.className=b.className;a.innerHTML=b.innerHTML;a.href=nativeHref(byId[selected],c);a.dataset.nativeContact=c;a.setAttribute('aria-label',c==='call'?'Call client':c==='text'?'Text client':'WhatsApp client');b.replaceWith(a)});if(detailTab==='activity')$('.activity-paper').insertAdjacentHTML('afterend',callArchive(byId[selected]));redactContactNumbers(document.body)};
const pageLeadsV4=renderLeads;renderLeads=function(){pageLeadsV4();$('.page-title').insertAdjacentHTML('beforeend',noticeButton())};
const followV4=renderFollowups;renderFollowups=function(){followV4();$('.page-title').insertAdjacentHTML('beforeend',noticeButton())};
function redactContactNumbers(root){const l=selected&&byId[selected];if(!l?.phone10)return;const forms=[String(l.phone10),phone(l.phone10),'+1'+l.phone10];const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(/SCRIPT|STYLE/.test(n.parentElement?.tagName))continue;for(const f of forms)if(n.textContent.includes(f))n.textContent=n.textContent.split(f).join('Contact available via Call / Text')}}
document.addEventListener('click',e=>{const link=e.target.closest('[data-native-contact]');if(link){const channel=link.dataset.nativeContact,l=byId[selected];if(!/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)){e.preventDefault();contact(channel)}else{contactEvent(l,channel);setTimeout(()=>{if(selected)renderDetail()},100)}return}const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-notifications'))noticeModal();if(b.dataset.noticeTab){noticeTab=b.dataset.noticeTab;noticeModal()}if(b.dataset.noticeOpen){const id=b.dataset.noticeOpen;if(noticeTab==='follow')local.noticeRead['follow-'+id]=today();close();openLead(id)}if(b.dataset.previewContact){const l=byId[selected];contactEvent(l,b.dataset.previewContact);close();renderDetail();toast('App opening simulated. No call or message sent.')}},false);
window.addEventListener('message',e=>{if(e.origin!==location.origin)return;if(e.data?.type==='arrival-demo'&&arrival){delete local.noticeRead['arrival-'+arrival];persist();updateBells()}if(e.data?.type==='reset-demo'){local.opened||={};local.noticeRead||={}}});
setInterval(()=>{document.querySelectorAll('[data-elapsed]').forEach(x=>x.textContent=elapsed(Number(x.dataset.elapsed)));updateBells()},30000);
document.title='Lead Manager';
// Initial rendering is performed by session.js after all layers are registered.
